Create Phishing app
geekcomputers/Python pull request #1504
Opened 2022-04-24 12:16 UTC by mhnasajpour

2022-04-25 10:10 UTC, DontEatThemCookies requested changes
I don't recommend pushing this, as this kind of code that can easily be misused for malicious purposes. At the very least, a disclaimer in the comments such as "Strictly for educational purposes only" could be inserted, but that still can't stop bad actors from maliciously using it. I'd rather not push this at all.

2022-04-25 11:11 UTC, slowy07 commented
yeah same to me sir @DontEatThemCookies, i think it become useless, and look that, its seem have some useless function and ddnt have explanation by commenting for each function

2022-06-14 12:14 UTC, closed without merging

2022-08-05 18:48 UTC, shaischaudhry approved these changes

2022-08-05 19:02 UTC, mhnasajpour commented
May you merge this?