Create bodymass.py
geekcomputers/Python pull request #1972
Opened 2023-08-24 21:09 UTC by erent8

thanks for project.

2023-08-24 21:09 UTC, erent8 commented
thanks for project.

2023-08-25 04:25 UTC, NitkarshChourasia requested changes

2023-08-25 04:25 UTC, NitkarshChourasia commented on bodymass.py
> +kilo = float (input("kilonuzu giriniz(örnek: 84.9): "))
Encapsulate it in function.

2023-08-25 04:25 UTC, NitkarshChourasia commented on bodymass.py
> +    print (f"vucut kitle indeksiniz: {vki} normalsiniz.")
If using so many if-elif-else statements, then use match-case, which is much more better.

2023-08-25 04:25 UTC, NitkarshChourasia commented on bodymass.py
> +elif vki < 40:
Don't use **Magic Numbers.**

2023-08-25 04:25 UTC, NitkarshChourasia commented on bodymass.py
> +    print("Yanlış değer girdiniz.")
use
```python
if __name__ == "__main__":
        return main()
```

2023-08-25 04:25 UTC, NitkarshChourasia commented on bodymass.py
> +vki = (kilo / (boy**2))
Please use a standard reading language.
# Please use **ENGLISH** language for writing programs with python, obviously.

2023-08-28 06:05 UTC, merged