Added docstrings
geekcomputers/Python pull request #1991
Opened 2023-10-04 16:52 UTC by AkhilYadavPadala

@OfficialAhmed 
Added docstrings for consistency and readable to beginners.

2023-10-04 18:37 UTC, NitkarshChourasia requested changes
Not good, a program to even submit to a repo.

2023-10-04 18:37 UTC, NitkarshChourasia commented on Calculator with simple ui.py
>  def add(x, y):
Add more functions or just remove the file.

2023-10-04 18:37 UTC, NitkarshChourasia commented on Calculator with simple ui.py
>  def divide(x, y):
Add error handling if divided by zero.
if num1 = n, where n > 0 and num2 = 0, then error will be returned. Handle it.

2023-10-04 18:37 UTC, NitkarshChourasia commented on Calculator with simple ui.py
> +    This function multiplies two numbers.
use class with simple name for the class, and make this methods inside it.

2023-10-04 18:37 UTC, NitkarshChourasia commented on Calculator with simple ui.py
> +    2
make it oop based, and use 
```python
if __name__ == "__main__":
        main()
```

2023-10-04 18:37 UTC, NitkarshChourasia commented on Calculator with simple ui.py
add other calculation type, make it worthwhile to contribute.

2023-10-04 18:37 UTC, NitkarshChourasia commented on Calculator with simple ui.py
while making class, add docstring to it.

2023-10-05 02:40 UTC, OfficialAhmed approved these changes
Can be improved but overall good work

2023-10-05 05:06 UTC, NitkarshChourasia approved these changes
Yes, overall a __good start__.
Keep up the good work.

2023-10-07 13:41 UTC, merged

2023-10-07 18:14 UTC, AkhilYadavPadala commented
@geekcomputers Could you add hacktoberfest , hacktoberfest-accepted labels to my PR?