Gc
geekcomputers/Python pull request #1994
Opened 2023-10-06 14:32 UTC by AkhilYadavPadala

@OfficialAhmed  @NitkarshChourasia 
I made changes.
Review my code :)_

2023-10-06 20:21 UTC, NitkarshChourasia commented
I will do by the morning afternoon of 7th October, 2023.

2023-10-07 03:32 UTC, OfficialAhmed requested changes
* Improper indentation from line **_86_** to **_101_** .Probably it won't interpret the code properly **_remove indentation_**.
* In line **__99__** `break` keyword is also indented incorrectly

_Double check the indentation please, the rest of the code works fine_

2023-10-07 05:25 UTC, NitkarshChourasia requested changes
Everything is perfect, just minor corrections and you are good to go.

2023-10-07 05:25 UTC, NitkarshChourasia commented on Calculator with simple ui.py
> +            print(calculator.subtract(num1, num2))
Use a IDE if possible while coding.
Also, Use a code formatter if possible.
If possible, enable code formatter when saving the file.
You can also format the code by ```black```.
to install just type in cmd ```pip install black```
then format the file using cmd by typing in cmd ```black file_name.py```
and worry not, there are many ways to format a file. This clicks with me, that's it.

2023-10-07 05:25 UTC, NitkarshChourasia commented on Calculator with simple ui.py
> +class Calculator:
Can add a docsting for class, here...too.

2023-10-07 05:25 UTC, NitkarshChourasia commented on Calculator with simple ui.py
>  print("2.Subtract")
```python
calculator = Calculator()

# A dictionary that maps the choices to the functions
operations = {
    "1": calculator.add,
    "2": calculator.subtract,
    "3": calculator.multiply,
    "4": calculator.divide
}

# A loop that asks the user for input until they enter a valid choice
while True:
    print("Select operation.")
    print("1.Add")
    print("2.Subtract")
    print("3.Multiply")
    print("4.Divide")

    choice = input("Enter choice(1/2/3/4): ")

    # Check if the choice is valid
    if choice in operations:
        
        # Ask the user for two numbers
        num1 = float(input("Enter first number: "))
        num2 = float(input("Enter second number: "))

        # Get the function by its key from the dictionary
        operation = operations.get(choice)

        # Call the function with the two numbers and print the result
        result = operation(num1, num2)
        print(f"The result is {result}")

        # Break out of the loop
        break
    else:
        # Print an error message and continue the loop
        print("Invalid input. Please try again.")
```

Understand these snippet.

2023-10-07 18:02 UTC, AkhilYadavPadala commented
I made corrections on indentation @OfficialAhmed .
Thanks for  the suggestion @NitkarshChourasia . I used black command to do so

2023-10-08 00:08 UTC, OfficialAhmed approved these changes

2023-10-08 04:24 UTC, NitkarshChourasia commented
> I made corrections on indentation @OfficialAhmed .
Thanks for the suggestion @NitkarshChourasia . I used black command to do so.

### Welcome.

2023-10-08 07:35 UTC, merged

2023-10-08 07:49 UTC, sarayusreeyadavpadala commented
@geekcomputers Would you mind adding hacktoberfest and hacktoberfest-accepted labels to my pull request.

2023-10-08 08:06 UTC, AkhilYadavPadala commented
@geekcomputers Would you mind adding hacktoberfest and hacktoberfest-accepted labels to my pull request.

2023-10-08 13:09 UTC, NitkarshChourasia commented
This repo has not been added to that program-fest. @AkhilYadavPadala